#ifndef OPENMPI2_TRANSMISSION_FLAGS_H
#define OPENMPI2_TRANSMISSION_FLAGS_H

const int FLAG_MULTIPLY_VECTOR_BROADCAST_SIZE = 1;
const int FLAG_MULTIPLY_VECTOR_BROADCAST_DATA = 2;
const int FLAG_SCATTER_SIZE = 3;
const int FLAG_SCATTER_DATA = 4;
const int FLAG_GATHER_DATA = 5;

#endif //OPENMPI2_TRANSMISSION_FLAGS_H
